In [1]:
import pandas as pd
import numpy as np

employees = pd.read_csv("../datasets/dimensions/Dim_Employee.csv")
departments = pd.read_csv("../datasets/dimensions/Dim_Department.csv")
locations = pd.read_csv("../datasets/dimensions/Dim_Location.csv")
job_levels = pd.read_csv("../datasets/dimensions/Dim_Job_Level.csv")

print("Dimension Tables Loaded")

Dimension Tables Loaded

In [2]:
import pandas as pd
import numpy as np

employees = pd.read_csv(
    "../datasets/dimensions/Dim_Employee.csv"
)

print(employees.shape)

(5000, 15)

In [3]:
salary_lookup = {
    1: (300000, 600000),
    2: (600000, 1200000),
    3: (1200000, 2500000),
    4: (2500000, 5000000)
}

In [4]:
import pandas as pd
import numpy as np

np.random.seed(42)

months = pd.date_range(
    start="2023-01-01",
    end="2025-12-01",
    freq="MS"
)

payroll_rows = []

payroll_id = 1

for month in months:

    for _, emp in employees.iterrows():

        min_sal, max_sal = salary_lookup[
            emp["comp_band_id"]
        ]

        annual_salary = np.random.randint(
            min_sal,
            max_sal + 1
        )

        monthly_salary = round(
            annual_salary / 12,
            2
        )

        bonus = round(
            monthly_salary *
            np.random.uniform(0, 0.20),
            2
        )

        overtime = round(
            np.random.uniform(0, 5000),
            2
        )

        deductions = round(
            monthly_salary *
            np.random.uniform(0.05, 0.15),
            2
        )

        gross_pay = round(
            monthly_salary +
            bonus +
            overtime,
            2
        )

        net_pay = round(
            gross_pay - deductions,
            2
        )

        payroll_rows.append({

            "payroll_fact_id": payroll_id,

            "employee_id": emp["employee_id"],

            "pay_period": month.strftime("%Y-%m"),

            "base_salary": monthly_salary,

            "bonus_amount": bonus,

            "overtime_amount": overtime,

            "deductions": deductions,

            "gross_pay": gross_pay,

            "net_pay": net_pay,

            "payment_status": np.random.choice(
                ["Paid","Paid","Paid","Paid","Delayed"],
                p=[0.24,0.24,0.24,0.24,0.04]
            )
        })

        payroll_id += 1

payroll = pd.DataFrame(payroll_rows)

print(payroll.shape)

(180000, 10)

In [5]:
print(payroll.head())

print("Rows:", len(payroll))

print(
    "Unique Employees:",
    payroll["employee_id"].nunique()
)

   payroll_fact_id  employee_id pay_period  base_salary  bonus_amount  \
0                1            1    2023-01    393259.17      62649.57
1                2            2    2023-01     61444.75       1917.01
2                3            3    2023-01     73180.58       9526.48
3                4            4    2023-01    203968.08       7417.30
4                5            5    2023-01     71566.25        330.10

   overtime_amount  deductions  gross_pay    net_pay payment_status
0           917.17    50325.02  456825.91  406500.89           Paid
1           290.42     8394.44   63652.18   55257.74           Paid
2           282.06     8942.66   82989.12   74046.46           Paid
3           917.02    16403.97  212302.40  195898.43           Paid
4          2623.87     6439.97   74520.22   68080.25           Paid
Rows: 180000
Unique Employees: 5000

In [6]:
payroll.to_csv(
    "../datasets/facts/Fact_Payroll.csv",
    index=False
)

print("Fact_Payroll Saved Successfully")

Fact_Payroll Saved Successfully

In [7]:
import os

print(os.listdir("../datasets/facts"))

['Fact_Payroll.csv']

In [8]:
payroll.shape

(180000, 10)

In [9]:
import pandas as pd
import numpy as np

employees = pd.read_csv(
    "../datasets/dimensions/Dim_Employee.csv"
)

print(employees.shape)

(5000, 15)

In [10]:
import pandas as pd
import numpy as np

np.random.seed(42)

months = pd.date_range(
    start="2023-01-01",
    end="2025-12-01",
    freq="MS"
)

attendance_rows = []

attendance_id = 1

for month in months:

    for _, emp in employees.iterrows():

        working_days = np.random.randint(20, 24)

        absent_days = np.random.randint(0, 4)

        leave_days = np.random.randint(0, 3)

        present_days = (
            working_days
            - absent_days
            - leave_days
        )

        present_days = max(present_days, 0)

        late_days = np.random.randint(0, 6)

        overtime_hours = round(
            np.random.uniform(0, 30),
            2
        )

        attendance_pct = round(
            (present_days / working_days) * 100,
            2
        )

        attendance_rows.append({

            "attendance_fact_id": attendance_id,

            "employee_id": emp["employee_id"],

            "attendance_month":
                month.strftime("%Y-%m"),

            "working_days": working_days,

            "present_days": present_days,

            "absent_days": absent_days,

            "leave_days": leave_days,

            "late_days": late_days,

            "overtime_hours": overtime_hours,

            "attendance_percentage":
                attendance_pct
        })

        attendance_id += 1

attendance = pd.DataFrame(
    attendance_rows
)

print(attendance.shape)

(180000, 10)

In [11]:
print(attendance.head())

print("Rows:", len(attendance))

print(
    "Unique Employees:",
    attendance["employee_id"].nunique()
)

   attendance_fact_id  employee_id attendance_month  working_days  \
0                   1            1          2023-01            22
1                   2            2          2023-01            20
2                   3            3          2023-01            22
3                   4            4          2023-01            22
4                   5            5          2023-01            21

   present_days  absent_days  leave_days  late_days  overtime_hours  \
0            19            3           0          2           23.39
1            17            2           1          2            3.00
2            19            3           0          3            4.29
3            21            1           0          1           21.66
4            19            1           1          3            5.50

   attendance_percentage
0                  86.36
1                  85.00
2                  86.36
3                  95.45
4                  90.48
Rows: 180000
Unique Employees: 5000

In [12]:
attendance.to_csv(
    "../datasets/facts/Fact_Attendance.csv",
    index=False
)

print(
    "Fact_Attendance Saved Successfully"
)

Fact_Attendance Saved Successfully

In [13]:
import os

print(
    os.listdir("../datasets/facts")
)

['Fact_Attendance.csv', 'Fact_Payroll.csv']

In [14]:
import os

print(
    os.listdir("../datasets/facts")
)

['Fact_Attendance.csv', 'Fact_Payroll.csv']

In [15]:
import pandas as pd
import numpy as np

np.random.seed(42)

review_dates = pd.date_range(
    start="2023-01-01",
    end="2025-12-31",
    freq="MS"
)

performance_rows = []

for perf_id in range(1, 20001):

    employee_id = np.random.randint(
        1,
        5001
    )

    performance_score = round(
        np.random.normal(3.5, 0.8),
        2
    )

    performance_score = min(
        max(performance_score, 1),
        5
    )

    goal_achievement = round(
        np.random.uniform(60, 120),
        2
    )

    competency_score = round(
        np.random.uniform(1, 5),
        2
    )

    manager_rating = round(
        np.random.uniform(1, 5),
        2
    )

    if performance_score >= 4.5:
        category = "Outstanding"
    elif performance_score >= 4.0:
        category = "Exceeds Expectations"
    elif performance_score >= 3.0:
        category = "Meets Expectations"
    elif performance_score >= 2.0:
        category = "Needs Improvement"
    else:
        category = "Poor"

    performance_rows.append({

        "performance_fact_id": perf_id,

        "employee_id": employee_id,

        "review_date":
            np.random.choice(review_dates),

        "review_period":
            np.random.choice(
                ["Q1","Q2","Q3","Q4"]
            ),

        "performance_score":
            performance_score,

        "goal_achievement_pct":
            goal_achievement,

        "competency_score":
            competency_score,

        "manager_rating":
            manager_rating,

        "performance_category":
            category
    })

performance = pd.DataFrame(
    performance_rows
)

print(performance.shape)

(20000, 9)

In [16]:
print(performance.head())

print(
    "Rows:",
    len(performance)
)

print(
    "Unique Employees:",
    performance["employee_id"]
    .nunique()
)

   performance_fact_id  employee_id review_date review_period  \
0                    1          861  2023-11-01            Q4
1                    2         3445  2023-02-01            Q4
2                    3         2434  2025-03-01            Q3
3                    4         2559  2023-03-01            Q1
4                    5         3891  2023-09-01            Q2

   performance_score  goal_achievement_pct  competency_score  manager_rating  \
0               3.93                 95.81              2.78            1.40
1               3.01                 96.07              3.83            1.08
2               3.13                 78.25              3.10            2.73
3               3.13                 68.37              2.17            2.47
4               3.08                 60.80              4.77            3.25

  performance_category
0   Meets Expectations
1   Meets Expectations
2   Meets Expectations
3   Meets Expectations
4   Meets Expectations
Rows: 20000
Unique Employees: 4905

In [17]:
performance.to_csv(
    "../datasets/facts/Fact_Performance.csv",
    index=False
)

print(
    "Fact_Performance Saved Successfully"
)

Fact_Performance Saved Successfully

In [18]:
import pandas as pd
import numpy as np

employees = pd.read_csv(
    "../datasets/dimensions/Dim_Employee.csv"
)

print(employees.shape)

(5000, 15)

In [19]:
import pandas as pd
import numpy as np

np.random.seed(42)

training_dates = pd.date_range(
    start="2023-01-01",
    end="2025-12-31",
    freq="D"
)

training_types = [
    "Technical",
    "Leadership",
    "Compliance",
    "HR",
    "Analytics",
    "Finance",
    "Operations",
    "Soft Skills"
]

training_rows = []

for training_id in range(1, 30001):

    training_rows.append({

        "training_fact_id": training_id,

        "employee_id":
            np.random.randint(1, 5001),

        "training_date":
            np.random.choice(training_dates),

        "training_type":
            np.random.choice(training_types),

        "training_hours":
            round(
                np.random.uniform(2, 40),
                2
            ),

        "training_cost":
            round(
                np.random.uniform(
                    1000,
                    50000
                ),
                2
            ),

        "completion_status":
            np.random.choice(
                [
                    "Completed",
                    "Completed",
                    "Completed",
                    "In Progress",
                    "Dropped"
                ]
            ),

        "assessment_score":
            round(
                np.random.uniform(
                    50,
                    100
                ),
                2
            ),

        "certification_received":
            np.random.choice(
                ["Yes", "No"],
                p=[0.35, 0.65]
            )
    })

training = pd.DataFrame(
    training_rows
)

print(training.shape)

(30000, 9)

In [20]:
print(training.head())

print(
    "Rows:",
    len(training)
)

print(
    "Unique Employees:",
    training["employee_id"]
    .nunique()
)

   training_fact_id  employee_id training_date training_type  training_hours  \
0                 1          861    2025-12-31     Analytics           24.68
1                 2         2920    2023-05-11       Finance            4.14
2                 3         4556    2023-01-22     Analytics           18.41
3                 4         2748    2025-09-02    Operations           19.33
4                 5         1529    2024-10-08     Analytics           19.12

   training_cost completion_status  assessment_score certification_received
0       22845.80         Completed             72.96                    Yes
1       36377.94         Completed             59.09                    Yes
2       15270.23         Completed             69.99                    Yes
3       39473.62         Completed             69.12                     No
4        1649.98         Completed             98.28                     No
Rows: 30000
Unique Employees: 4986

In [21]:
training.to_csv(
    "../datasets/facts/Fact_Training.csv",
    index=False
)

print(
    "Fact_Training Saved Successfully"
)

Fact_Training Saved Successfully

In [22]:
import pandas as pd
import numpy as np

employees = pd.read_csv(
    "../datasets/dimensions/Dim_Employee.csv"
)

print(employees.shape)

(5000, 15)

In [23]:
import pandas as pd
import numpy as np

np.random.seed(42)

survey_dates = pd.date_range(
    start="2023-01-01",
    end="2025-12-31",
    freq="D"
)

engagement_rows = []

for eid in range(1, 60001):

    engagement_score = round(
        np.random.uniform(1, 5),
        2
    )

    satisfaction_score = round(
        np.random.uniform(1, 5),
        2
    )

    wlb_score = round(
        np.random.uniform(1, 5),
        2
    )

    manager_support = round(
        np.random.uniform(1, 5),
        2
    )

    burnout_index = round(
        np.random.uniform(0, 100),
        2
    )

    recommend_flag = np.random.choice(
        ["Yes", "No"],
        p=[0.65, 0.35]
    )

    engagement_rows.append({

        "engagement_fact_id": eid,

        "employee_id":
            np.random.randint(1, 5001),

        "survey_date":
            np.random.choice(survey_dates),

        "engagement_score":
            engagement_score,

        "satisfaction_score":
            satisfaction_score,

        "work_life_balance_score":
            wlb_score,

        "manager_support_score":
            manager_support,

        "burnout_index":
            burnout_index,

        "recommend_company_flag":
            recommend_flag
    })

engagement = pd.DataFrame(
    engagement_rows
)

print(engagement.shape)

(60000, 9)

In [24]:
print(engagement.head())

print("Rows:", len(engagement))

print(
    "Unique Employees:",
    engagement["employee_id"].nunique()
)

   engagement_fact_id  employee_id survey_date  engagement_score  \
0                   1         4427  2023-03-29              2.50
1                   2         2434  2025-08-13              2.33
2                   3         2048  2024-11-30              1.73
3                   4         3203  2024-10-08              2.47
4                   5         2613  2025-06-16              1.68

   satisfaction_score  work_life_balance_score  manager_support_score  \
0                4.80                     3.93                   3.39
1                1.57                     3.60                   1.23
2                2.22                     3.10                   2.73
3                2.82                     4.14                   1.80
4                1.26                     4.80                   4.86

   burnout_index recommend_company_flag
0          15.60                    Yes
1          72.20                     No
2          29.12                    Yes
3          51.42                    Yes
4          80.84                    Yes
Rows: 60000
Unique Employees: 5000

In [25]:
engagement.to_csv(
    "../datasets/facts/Fact_Engagement.csv",
    index=False
)

print("Fact_Engagement Saved Successfully")

Fact_Engagement Saved Successfully

In [26]:
import pandas as pd
import numpy as np

np.random.seed(42)

roles = pd.read_csv("../datasets/dimensions/Dim_Role.csv")

print(roles.shape)

(100, 5)

In [27]:
import pandas as pd
import numpy as np

np.random.seed(42)

application_dates = pd.date_range(
    start="2023-01-01",
    end="2025-12-31",
    freq="D"
)

sources = [
    "LinkedIn",
    "Naukri",
    "Referral",
    "Company Website",
    "Campus",
    "Agency"
]

stages = [
    "Applied",
    "Screening",
    "Interview",
    "HR Round",
    "Offer",
    "Hired",
    "Rejected"
]

recruitment_rows = []

for i in range(1, 12001):

    hired_flag = np.random.choice([0, 1], p=[0.75, 0.25])

    offer_status = "Offered" if hired_flag == 1 else np.random.choice(["Rejected", "Hold"])

    recruitment_rows.append({

        "recruitment_fact_id": i,

        "candidate_id": f"CAND{i:06d}",

        "job_role_id": np.random.randint(1, 101),

        "application_date": np.random.choice(application_dates),

        "recruitment_source": np.random.choice(sources),

        "stage": np.random.choice(stages),

        "interview_score": round(np.random.uniform(1, 5), 2),

        "offer_status": offer_status,

        "hired_flag": hired_flag,

        "time_to_hire_days": np.random.randint(7, 60)
    })

recruitment = pd.DataFrame(recruitment_rows)

print(recruitment.shape)

(12000, 10)

In [28]:
print(recruitment.head())

print("Rows:", len(recruitment))

print("Hired Rate:", recruitment["hired_flag"].mean())

   recruitment_fact_id candidate_id  job_role_id application_date  \
0                    1   CAND000001           15       2025-12-31
1                    2   CAND000002           88       2025-05-21
2                    3   CAND000003           38       2024-01-21
3                    4   CAND000004           49       2024-04-19
4                    5   CAND000005           15       2023-07-09

  recruitment_source     stage  interview_score offer_status  hired_flag  \
0             Campus     Offer             1.62     Rejected           0
1           Referral     Hired             1.23     Rejected           0
2    Company Website     Offer             3.47      Offered           1
3           Referral  Rejected             1.56     Rejected           0
4             Agency  Rejected             3.47      Offered           1

   time_to_hire_days
0                 25
1                 30
2                 28
3                 34
4                 50
Rows: 12000
Hired Rate: 0.25133333333333335

In [29]:
recruitment.to_csv(
    "../datasets/facts/Fact_Recruitment.csv",
    index=False
)

print("Fact_Recruitment Saved Successfully")

Fact_Recruitment Saved Successfully

In [30]:
import pandas as pd
import numpy as np

np.random.seed(42)

employees = pd.read_csv("../datasets/dimensions/Dim_Employee.csv")

managers = pd.read_csv("../datasets/dimensions/Dim_Manager.csv")

print(employees.shape, managers.shape)

(5000, 15) (200, 5)

In [31]:
import pandas as pd
import numpy as np

np.random.seed(42)

change_dates = pd.date_range(
    start="2023-01-01",
    end="2025-12-31",
    freq="D"
)

change_types = [
    "Annual Increment",
    "Promotion",
    "Market Adjustment",
    "Role Change"
]

reasons = [
    "Performance Based",
    "Retention Strategy",
    "Market Correction",
    "Promotion Cycle",
    "Internal Mobility"
]

comp_changes = []

for i in range(1, 8001):

    emp_id = np.random.randint(1, 5001)

    old_salary = np.random.randint(30000, 200000)

    change_type = np.random.choice(change_types, p=[0.5, 0.2, 0.2, 0.1])

    if change_type == "Promotion":
        change_percent = np.random.uniform(10, 40)
    elif change_type == "Annual Increment":
        change_percent = np.random.uniform(3, 12)
    else:
        change_percent = np.random.uniform(-5, 15)

    new_salary = round(old_salary * (1 + change_percent/100), 2)

    comp_changes.append({

        "comp_change_fact_id": i,

        "employee_id": emp_id,

        "change_date": np.random.choice(change_dates),

        "change_type": change_type,

        "old_salary": old_salary,

        "new_salary": new_salary,

        "change_amount": round(new_salary - old_salary, 2),

        "change_percent": round(change_percent, 2),

        "reason": np.random.choice(reasons),

        "approved_by_manager_id": np.random.randint(1, 201)
    })

comp_change = pd.DataFrame(comp_changes)

print(comp_change.shape)

(8000, 10)

In [32]:
print(comp_change.head())

print("Rows:", len(comp_change))

print("Avg Change %:", comp_change["change_percent"].mean())

   comp_change_fact_id  employee_id change_date        change_type  \
0                    1          861  2023-05-02  Market Adjustment
1                    2         3445  2023-12-10          Promotion
2                    3         2434  2023-01-22        Role Change
3                    4          475  2024-11-30   Annual Increment
4                    5         1268  2024-10-08   Annual Increment

   old_salary  new_salary  change_amount  change_percent             reason  \
0      133694   143016.71        9322.71            6.97  Market Correction
1       46023    51404.17        5381.17           11.69    Promotion Cycle
2       35311    37906.23        2595.23            7.35  Internal Mobility
3      186730   193116.15        6386.15            3.42  Market Correction
4       61551    68161.25        6610.25           10.74  Internal Mobility

   approved_by_manager_id
0                      75
1                     158
2                      89
3                     108
4                      73
Rows: 8000
Avg Change %: 10.328665

In [33]:
comp_change.to_csv(
    "../datasets/facts/Fact_Comp_Change.csv",
    index=False
)

print("Fact_Comp_Change Saved Successfully")

Fact_Comp_Change Saved Successfully

In [34]:
comp_change.to_csv(
    "../datasets/facts/Fact_Comp_Change.csv",
    index=False
)

print("Fact_Comp_Change Saved Successfully")

Fact_Comp_Change Saved Successfully

In [35]:
import pandas as pd
import numpy as np

np.random.seed(42)

employees = pd.read_csv("../datasets/dimensions/Dim_Employee.csv")

print(employees.shape)

(5000, 15)

In [36]:
import pandas as pd
import numpy as np

np.random.seed(42)

movement_dates = pd.date_range(
    start="2023-01-01",
    end="2025-12-31",
    freq="D"
)

movement_types = [
    "Internal Transfer",
    "Promotion",
    "Role Change",
    "Location Change"
]

reasons = [
    "Career Growth",
    "Business Requirement",
    "Performance Based",
    "Restructuring",
    "Employee Request"
]

mobility_rows = []

for i in range(1, 5001):

    emp_id = np.random.randint(1, 5001)

    from_dept = np.random.randint(1, 21)
    to_dept = np.random.randint(1, 21)

    from_role = np.random.randint(1, 101)
    to_role = np.random.randint(1, 101)

    from_loc = np.random.randint(1, 11)
    to_loc = np.random.randint(1, 11)

    mobility_rows.append({

        "mobility_fact_id": i,

        "employee_id": emp_id,

        "movement_date": np.random.choice(movement_dates),

        "movement_type": np.random.choice(movement_types),

        "from_department_id": from_dept,

        "to_department_id": to_dept,

        "from_role_id": from_role,

        "to_role_id": to_role,

        "from_location_id": from_loc,

        "to_location_id": to_loc,

        "reason": np.random.choice(reasons)
    })

mobility = pd.DataFrame(mobility_rows)

print(mobility.shape)

(5000, 11)

In [37]:
print(mobility.head())

print("Rows:", len(mobility))

print("Unique Employees:", mobility["employee_id"].nunique())

   mobility_fact_id  employee_id movement_date      movement_type  \
0                 1          861    2023-05-02        Role Change
1                 2         3445    2025-02-08    Location Change
2                 3         2434    2024-04-19        Role Change
3                 4         2048    2025-04-11  Internal Transfer
4                 5         3557    2024-01-23  Internal Transfer

   from_department_id  to_department_id  from_role_id  to_role_id  \
0                  15                11            72          61
1                   4                 8            24           3
2                   1                12            58          22
3                  16                15            62          62
4                  19                 7            21          73

   from_location_id  to_location_id                reason
0                 5               7     Performance Based
1                 6               5         Restructuring
2                 9               1  Business Requirement
3                 3               7     Performance Based
4                 7               2         Restructuring
Rows: 5000
Unique Employees: 3173

In [38]:
mobility.to_csv(
    "../datasets/facts/Fact_Mobility.csv",
    index=False
)

print("Fact_Mobility Saved Successfully")

Fact_Mobility Saved Successfully

In [39]:
mobility.to_csv(
    "../datasets/facts/Fact_Mobility.csv",
    index=False
)

print("Fact_Mobility Saved Successfully")

Fact_Mobility Saved Successfully

In [40]:
import pandas as pd
import numpy as np

np.random.seed(42)

employees = pd.read_csv("../datasets/dimensions/Dim_Employee.csv")

print(employees.shape)

(5000, 15)

In [41]:
import pandas as pd
import numpy as np

np.random.seed(42)

months = pd.date_range(
    start="2023-01-01",
    end="2025-12-01",
    freq="MS"
)

productivity_rows = []

prod_id = 1

for month in months:

    for _, emp in employees.iterrows():

        output_score = round(np.random.uniform(50, 100), 2)

        tasks_completed = np.random.randint(5, 50)

        quality_score = round(np.random.uniform(1, 5), 2)

        efficiency_score = round(np.random.uniform(1, 5), 2)

        kpi = round(np.random.uniform(60, 120), 2)

        if kpi >= 110:
            rating = "Excellent"
        elif kpi >= 90:
            rating = "Good"
        elif kpi >= 70:
            rating = "Average"
        else:
            rating = "Poor"

        productivity_rows.append({

            "productivity_fact_id": prod_id,

            "employee_id": emp["employee_id"],

            "productivity_month": month.strftime("%Y-%m"),

            "output_score": output_score,

            "tasks_completed": tasks_completed,

            "quality_score": quality_score,

            "efficiency_score": efficiency_score,

            "kpi_achievement_pct": kpi,

            "productivity_rating": rating
        })

        prod_id += 1

productivity = pd.DataFrame(productivity_rows)

print(productivity.shape)

(180000, 9)

In [42]:
print(productivity.head())

print("Rows:", len(productivity))

print("Unique Employees:", productivity["employee_id"].nunique())

   productivity_fact_id  employee_id productivity_month  output_score  \
0                     1            1            2023-01         68.73
1                     2            2            2023-01         72.29
2                     3            3            2023-01         85.40
3                     4            4            2023-01         50.04
4                     5            5            2023-01         51.15

   tasks_completed  quality_score  efficiency_score  kpi_achievement_pct  \
0               33           1.73              4.12                95.81
1               27           1.23              4.46                96.07
2               26           1.23              3.89               116.31
3               25           3.47              3.45                60.42
4               31           3.45              1.56                77.53

  productivity_rating
0                Good
1                Good
2           Excellent
3                Poor
4             Average
Rows: 180000
Unique Employees: 5000

In [43]:
productivity.to_csv(
    "../datasets/facts/Fact_Productivity.csv",
    index=False
)

print("Fact_Productivity Saved Successfully")

Fact_Productivity Saved Successfully

In [44]:
productivity.to_csv(
    "../datasets/facts/Fact_Productivity.csv",
    index=False
)

print("Fact_Productivity Saved Successfully")

Fact_Productivity Saved Successfully

In [45]:
import pandas as pd
import numpy as np

np.random.seed(42)

exit_dates = pd.date_range(
    start="2023-01-01",
    end="2025-12-31",
    freq="D"
)

exit_types = [
    "Resignation",
    "Termination",
    "Retirement",
    "Layoff"
]

exit_reasons = [
    "Better Opportunity",
    "Compensation Issue",
    "Work-Life Balance",
    "Manager Conflict",
    "Relocation",
    "Career Growth",
    "Performance Issue"
]

exit_rows = []

for i in range(1, 1001):

    emp_id = np.random.randint(1, 5001)

    hire_date = pd.Timestamp("2023-01-01") + pd.to_timedelta(
        np.random.randint(0, 1096),
        unit="D"
    )

    exit_date = np.random.choice(exit_dates)

    tenure_days = max((pd.Timestamp(exit_date) - hire_date).days, 30)

    exit_rows.append({

        "exit_fact_id": i,

        "employee_id": emp_id,

        "exit_date": exit_date,

        "exit_type": np.random.choice(exit_types, p=[0.75, 0.15, 0.05, 0.05]),

        "exit_reason": np.random.choice(exit_reasons),

        "tenure_days": tenure_days,

        "exit_interview_score": round(np.random.uniform(1, 5), 2),

        "re_hire_eligibility": np.random.choice(["Yes", "No"], p=[0.3, 0.7]),

        "replacement_hired_flag": np.random.choice([0, 1], p=[0.4, 0.6])
    })

exit_df = pd.DataFrame(exit_rows)

print(exit_df.shape)

(1000, 9)

In [46]:
print(exit_df.head())

print("Rows:", len(exit_df))

print("Unique Employees:", exit_df["employee_id"].nunique())

   exit_fact_id  employee_id  exit_date    exit_type         exit_reason  \
0             1          861 2025-11-10  Resignation   Work-Life Balance
1             2         2920 2025-02-08  Resignation       Career Growth
2             3         4556 2023-09-10  Resignation  Better Opportunity
3             4         2748 2023-07-09  Resignation       Career Growth
4             5         3203 2023-01-21  Resignation  Compensation Issue

   tenure_days  exit_interview_score re_hire_eligibility  \
0           30                  1.40                  No
1          639                  1.85                 Yes
2          231                  3.10                  No
3           30                  1.80                  No
4           30                  4.80                  No

   replacement_hired_flag
0                       0
1                       0
2                       0
3                       1
4                       1
Rows: 1000
Unique Employees: 906

In [47]:
exit_df.to_csv(
    "../datasets/facts/Fact_Exit.csv",
    index=False
)

print("Fact_Exit Saved Successfully")

Fact_Exit Saved Successfully

In [48]:
import pandas as pd

df = pd.read_csv("../datasets/facts/Fact_Payroll.csv")

print(df.shape)
df.head()

(180000, 10)

,payroll_fact_id,employee_id,pay_period,base_salary,bonus_amount,overtime_amount,deductions,gross_pay,net_pay,payment_status
0,1,1,2023-01,393259.17,62649.57,917.17,50325.02,456825.91,406500.89,Paid
1,2,2,2023-01,61444.75,1917.01,290.42,8394.44,63652.18,55257.74,Paid
2,3,3,2023-01,73180.58,9526.48,282.06,8942.66,82989.12,74046.46,Paid
3,4,4,2023-01,203968.08,7417.30,917.02,16403.97,212302.40,195898.43,Paid
4,5,5,2023-01,71566.25,330.10,2623.87,6439.97,74520.22,68080.25,Paid

In [49]:
df.columns.tolist()

['payroll_fact_id',
 'employee_id',
 'pay_period',
 'base_salary',
 'bonus_amount',
 'overtime_amount',
 'deductions',
 'gross_pay',
 'net_pay',
 'payment_status']

In [1]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine

engine = create_engine(
    "mysql+pymysql://root:yourpassword@localhost:3306/hr_analytics"
)

In [4]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine

engine = create_engine(
    "mysql+pymysql://root:yourpassword@localhost:3306/hr_analytics_dw"
)

In [6]:
df = pd.read_sql("SELECT * FROM recruitment_feature_engineered", engine)
print(df.head())

   recruitment_fact_id candidate_id  job_role_id application_date  \
0                    1   CAND000001           15       2025-12-31
1                    2   CAND000002           88       2025-05-21
2                    3   CAND000003           38       2024-01-21
3                    4   CAND000004           49       2024-04-19
4                    5   CAND000005           15       2023-07-09

  recruitment_source     stage  interview_score offer_status  hired_flag  \
0             CAMPUS     OFFER             1.62     REJECTED           0
1           REFERRAL     HIRED             1.23     REJECTED           0
2    COMPANY WEBSITE     OFFER             3.47      OFFERED           1
3           REFERRAL  REJECTED             1.56     REJECTED           0
4             AGENCY  REJECTED             3.47      OFFERED           1

   time_to_hire_days score_band  fast_hire_flag time_to_hire_category  \
0                 25       Poor               0                Normal
1                 30       Poor               0                Normal
2                 28       Good               0                Normal
3                 34       Poor               0                  Slow
4                 50       Good               0                  Slow

   high_quality_candidate  offer_accepted  hiring_efficiency_score  \
0                       0               0                 0.062308
1                       0               0                 0.039677
2                       0               0                 0.119655
3                       0               0                 0.044571
4                       0               0                 0.068039

   source_rank candidate_status  hiring_delay_flag
0          5.0         Rejected                  0
1          2.0         Rejected                  0
2          3.0            Hired                  0
3          2.0         Rejected                  1
4          4.0            Hired                  1

In [7]:
print(df.columns.tolist())

['recruitment_fact_id', 'candidate_id', 'job_role_id', 'application_date', 'recruitment_source', 'stage', 'interview_score', 'offer_status', 'hired_flag', 'time_to_hire_days', 'score_band', 'fast_hire_flag', 'time_to_hire_category', 'high_quality_candidate', 'offer_accepted', 'hiring_efficiency_score', 'source_rank', 'candidate_status', 'hiring_delay_flag']

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 12000 entries, 0 to 11999
Data columns (total 19 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   recruitment_fact_id      12000 non-null  int64
 1   candidate_id             12000 non-null  str
 2   job_role_id              12000 non-null  int64
 3   application_date         12000 non-null  datetime64[us]
 4   recruitment_source       12000 non-null  str
 5   stage                    12000 non-null  str
 6   interview_score          12000 non-null  float64
 7   offer_status             12000 non-null  str
 8   hired_flag               12000 non-null  int64
 9   time_to_hire_days        12000 non-null  int64
 10  score_band               12000 non-null  str
 11  fast_hire_flag           12000 non-null  int64
 12  time_to_hire_category    12000 non-null  str
 13  high_quality_candidate   12000 non-null  int64
 14  offer_accepted           12000 non-null  int64
 15  hiring_efficiency_score  12000 non-null  float64
 16  source_rank              12000 non-null  float64
 17  candidate_status         12000 non-null  str
 18  hiring_delay_flag        12000 non-null  int64
dtypes: datetime64[us](1), float64(3), int64(8), str(7)
memory usage: 2.3 MB

In [9]:
df.head(10)

,recruitment_fact_id,candidate_id,job_role_id,application_date,recruitment_source,stage,interview_score,offer_status,hired_flag,time_to_hire_days,score_band,fast_hire_flag,time_to_hire_category,high_quality_candidate,offer_accepted,hiring_efficiency_score,source_rank,candidate_status,hiring_delay_flag
0,1,CAND000001,15,2025-12-31,CAMPUS,OFFER,1.62,REJECTED,0,25,Poor,0,Normal,0,0,0.062308,5.0,Rejected,0
1,2,CAND000002,88,2025-05-21,REFERRAL,HIRED,1.23,REJECTED,0,30,Poor,0,Normal,0,0,0.039677,2.0,Rejected,0
2,3,CAND000003,38,2024-01-21,COMPANY WEBSITE,OFFER,3.47,OFFERED,1,28,Good,0,Normal,0,0,0.119655,3.0,Hired,0
3,4,CAND000004,49,2024-04-19,REFERRAL,REJECTED,1.56,REJECTED,0,34,Poor,0,Slow,0,0,0.044571,2.0,Rejected,1
4,5,CAND000005,15,2023-07-09,AGENCY,REJECTED,3.47,OFFERED,1,50,Good,0,Slow,0,0,0.068039,4.0,Hired,1
5,6,CAND000006,3,2024-10-08,CAMPUS,APPLIED,1.26,HOLD,0,10,Poor,1,Fast,0,0,0.114545,5.0,Rejected,0
6,7,CAND000007,14,2023-08-30,NAUKRI,APPLIED,1.06,OFFERED,1,8,Poor,1,Fast,0,0,0.117778,6.0,Hired,0
7,8,CAND000008,60,2024-05-23,REFERRAL,HIRED,2.56,REJECTED,0,56,Average,0,Slow,0,0,0.044912,2.0,Rejected,1
8,9,CAND000009,6,2024-07-19,NAUKRI,HR ROUND,1.74,HOLD,0,24,Poor,0,Normal,0,0,0.069600,6.0,Rejected,0
9,10,CAND000010,34,2023-07-21,AGENCY,HR ROUND,3.39,OFFERED,1,54,Good,0,Slow,0,0,0.061636,4.0,Hired,1

In [10]:
df["high_quality_candidate"] = np.where(
    df["interview_score"] >= 3.5,
    1,
    0
)

In [11]:
df["offer_accepted"] = np.where(
    df["offer_status"] == "OFFERED",
    1,
    0
)

In [12]:
df["hiring_efficiency_score"] = (
    (df["interview_score"] * 20)
    +
    (100 - df["time_to_hire_days"])
)

In [13]:
df["hiring_efficiency_score"] = (
    df["hiring_efficiency_score"]
    .clip(0, 100)
)

In [14]:
df["score_band"] = np.select(
    [
        df["interview_score"] < 2,
        (df["interview_score"] >= 2) & (df["interview_score"] < 3),
        (df["interview_score"] >= 3) & (df["interview_score"] < 4),
        df["interview_score"] >= 4
    ],
    [
        "Poor",
        "Average",
        "Good",
        "Excellent"
    ],
    default="Average"
)

In [15]:
df["high_quality_candidate"] = np.where(
    df["interview_score"] >= 4,
    1,
    0
)

In [16]:
df["offer_accepted"] = np.where(
    df["offer_status"] == "OFFERED",
    1,
    0
)

In [17]:
df["hiring_efficiency_score"] = (
    (df["interview_score"] * 15)
    +
    (100 - df["time_to_hire_days"])
)

In [18]:
df["hiring_efficiency_score"] = df["hiring_efficiency_score"].clip(0,100)

In [19]:
print(df[[
    "interview_score",
    "score_band",
    "high_quality_candidate",
    "offer_status",
    "offer_accepted",
    "time_to_hire_days",
    "hiring_efficiency_score"
]].head(20))

    interview_score score_band  high_quality_candidate offer_status  \
0              1.62       Poor                       0     REJECTED
1              1.23       Poor                       0     REJECTED
2              3.47       Good                       0      OFFERED
3              1.56       Poor                       0     REJECTED
4              3.47       Good                       0      OFFERED
5              1.26       Poor                       0         HOLD
6              1.06       Poor                       0      OFFERED
7              2.56    Average                       0     REJECTED
8              1.74       Poor                       0         HOLD
9              3.39       Good                       0      OFFERED
10             2.55    Average                       0         HOLD
11             3.17       Good                       0         HOLD
12             2.17    Average                       0     REJECTED
13             1.30       Poor                       0         HOLD
14             1.38       Poor                       0         HOLD
15             3.24       Good                       0     REJECTED
16             4.08  Excellent                       1         HOLD
17             1.13       Poor                       0     REJECTED
18             4.02  Excellent                       1     REJECTED
19             2.18    Average                       0      OFFERED

    offer_accepted  time_to_hire_days  hiring_efficiency_score
0                0                 25                    99.30
1                0                 30                    88.45
2                1                 28                   100.00
3                0                 34                    89.40
4                1                 50                   100.00
5                0                 10                   100.00
6                1                  8                   100.00
7                0                 56                    82.40
8                0                 24                   100.00
9                1                 54                    96.85
10               0                 24                   100.00
11               0                 47                   100.00
12               0                 17                   100.00
13               0                 45                    74.50
14               0                 29                    91.70
15               0                 41                   100.00
16               0                 45                   100.00
17               0                 45                    71.95
18               0                 42                   100.00
19               1                 59                    73.70

In [20]:
df.to_sql(
    "recruitment_feature_engineered",
    engine,
    if_exists="replace",
    index=False
)

12000

In [21]:
df.to_csv(
    "Recruitment_Feature_Engineered.csv",
    index=False
)

In [22]:
import os

print(os.getcwd())

C:\Users\Admin\HR_Analytics_Project\notebooks

In [31]:
df.to_csv(
    r"C:\Users\Admin\HR_Analytics_Project\datasets\Recruitment_Feature_Engineered.csv",
    index=False
)

In [33]:
df.to_csv(
    r"C:\Users\Admin\HR_Analytics_Project\datasets\Recruitment_Feature_Engineered.csv",
    index=False
)

In [28]:
import os

print(os.getcwd())

C:\Users\Admin\HR_Analytics_Project\notebooks

In [29]:
import os

print(os.path.exists(r"C:\Users\Admin\Documents\HR_Analytics_Project\datasets"))

False

In [34]:
import os

print(os.listdir(r"C:\Users\Admin\HR_Analytics_Project\datasets"))

['clean_dim_date.csv', 'clean_dim_role.csv', 'dimensions', 'facts', 'Recruitment_Feature_Engineered.csv', 'supporting']

In [35]:
import numpy as np

df["stage"] = np.select(
    [
        df["hired_flag"] == 1,
        df["offer_status"] == "OFFERED",
        df["offer_status"] == "HOLD",
        df["offer_status"] == "REJECTED"
    ],
    [
        "HIRED",
        "OFFER",
        "HR ROUND",
        "REJECTED"
    ],
    default="APPLIED"
)

In [37]:
df.to_csv(
    "Recruitment_Feature_Engineered.csv",
    index=False
)

In [39]:
df.to_csv(
    r"C:\Users\Admin\HR_Analytics_Project\datasets\Recruitment_Feature_Engineered.csv",
    index=False
)

In [40]:
df["stage"] = np.select(
    [
        df["hired_flag"] == 1,
        df["offer_status"] == "OFFERED",
        df["interview_score"] > 0
    ],
    [
        "HIRED",
        "OFFER",
        "INTERVIEW"
    ],
    default="APPLIED"
)

In [41]:
print(df["stage"].value_counts())

stage
INTERVIEW    8984
HIRED        3016
Name: count, dtype: int64

In [42]:
import numpy as np

# Set seed for reproducibility
np.random.seed(42)

# Default everyone as APPLIED
df["stage"] = "APPLIED"

# Candidates with interview score >= 2.0 move to INTERVIEW
df.loc[df["interview_score"] >= 2.0, "stage"] = "INTERVIEW"

# Candidates with OFFERED status move to OFFER
df.loc[df["offer_status"] == "OFFERED", "stage"] = "OFFER"

# Hired candidates move to HIRED
df.loc[df["hired_flag"] == 1, "stage"] = "HIRED"

print(df["stage"].value_counts())

stage
INTERVIEW    6737
HIRED        3016
APPLIED      2247
Name: count, dtype: int64

In [43]:
import numpy as np

# Default stage
df["stage"] = "APPLIED"

# Interview stage
df.loc[df["interview_score"] >= 2.0, "stage"] = "INTERVIEW"

# Offer stage
df.loc[df["offer_status"] == "OFFERED", "stage"] = "OFFER"

# Hired stage
df.loc[df["hired_flag"] == 1, "stage"] = "HIRED"

print(df["stage"].value_counts())

stage
INTERVIEW    6737
HIRED        3016
APPLIED      2247
Name: count, dtype: int64

In [44]:
df["candidate_status"] = np.select(
    [
        df["hired_flag"] == 1,
        df["offer_status"] == "OFFERED",
        df["offer_status"] == "HOLD"
    ],
    [
        "Hired",
        "Offer Pending",
        "On Hold"
    ],
    default="Rejected"
)

In [45]:
df["offer_accepted"] = np.where(
    (df["offer_status"] == "OFFERED") &
    (df["hired_flag"] == 1),
    1,
    0
)

In [47]:
df.to_csv(
    "Recruitment_Feature_Engineered.csv",
    index=False
)

In [48]:
df.to_csv(
    r"C:\Users\Admin\HR_Analytics_Project\datasets\Recruitment_Feature_Engineered.csv",
    index=False
)